title: my little slice of the world wide web
author: Kevin
description: This is a place for my thoughts, projects, and other stuff, free from the rat race that is the modern web.
permalink: none
markdown: kramdown
kramdown:
    smart_quotes: ["apos", "apos", "quot", "quot"]
