title: Personal Site
author: Kevin Nel
description: My home on the world wide web.
permalink: pretty
markdown: kramdown
#kramdown:
#    syntax_highlighter: coderay
#    smart_quotes: ["apos", "apos", "quot", "quot"]
# Build settings
#theme: minima
plugins:
 - jekyll-feed

collections:
  gear:
    output: true
    description: A list of my stuff that I find cool (kinda like show and tell I guess).
    layout: gear
  library:
    output: true
    description: A collection of links for interesting things.
  software:
    output: true
    description: Some pages that I keep updated with software tips.
  projects:
    output: true
    description: Buildlogs and the like.
  playlists:
    output: true
    description: Some playlists I've made.


defaults:
  -
    scope:
      path: ""
      type: "gear"
    values:
      layout: "collection"
  -
    scope:
      path: ""
      type: "library"
    values:
      layout: "collection"
  -
    scope:
      path: ""
      type: "software"
    values:
      layout: "collection"
  -
    scope:
      path: ""
      type: "projects"
    values:
      layout: "collection"
  -
    scope:
      path: ""
      type: "playlists"
    values:
      layout: "collection"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
